if: tag IS blank

language: java

sudo: false

jdk:
  - openjdk11

install:
  - chmod a+x ./gradlew
  - chmod a+x ./travis-build.sh

cache:
  directories:
    - $HOME/.gradle

script:
  - ./travis-build.sh
